# Jekyll config
name: Nicolas Gautron - Back-end developer - architect
description: 10 years of experience in PHP. Open to all technologies.
defaults:
  - scope:
      path: ""
    values:
      image: /assets/NicolasGautron.jpeg
markdown: GFM
plugins:
  - jemoji